import './globals.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import TanstackProvider from '../tanstack/TanstackProvider'
import Navbar from './components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <TanstackProvider>
          <div className="container">
            {children}
          </div>
        </TanstackProvider>
      </body>
    </html>
  )
}
