// data/CompaniesDummyData.ts

import { CompanyUser, UserType } from '@/models/User';

const companies: CompanyUser[] = [
  {
    id: '1',
    name: 'SoftVision',
    email: 'info@softvision.cz',
    phone: '+420 123 456 789',
    location: 'Prague, Czech Republic',
    type: UserType.Company,
    registeredAt: new Date('2021-03-01'),
    updatedAt: new Date(),
    companyName: 'SoftVision',
    website: 'https://softvision.cz',
    description: 'Czech software development agency specializing in web and mobile apps.',
    logoUrl: '/logos/softvision.png',
    industry: 'IT Services',
    size: 85,
  },
  {
    id: '2',
    name: 'CodeRealm GmbH',
    email: 'contact@coderealm.de',
    phone: '+49 30 9876 5432',
    location: 'Berlin, Germany',
    type: UserType.Company,
    registeredAt: new Date('2020-08-10'),
    updatedAt: new Date(),
    companyName: 'CodeRealm GmbH',
    website: 'https://coderealm.de',
    description: 'Full-stack development firm offering enterprise solutions in Java and React.',
    logoUrl: '/logos/coderealm.png',
    industry: 'Software Development',
    size: 120,
  },
  {
    id: '3',
    name: 'TechAustria',
    email: 'office@techaustria.at',
    phone: '+43 1 2345 6789',
    location: 'Vienna, Austria',
    type: UserType.Company,
    registeredAt: new Date('2019-11-20'),
    updatedAt: new Date(),
    companyName: 'TechAustria',
    website: 'https://techaustria.at',
    description: 'Austrian tech firm focused on IoT, embedded systems, and AI.',
    logoUrl: '/logos/techaustria.png',
    industry: 'Embedded Systems',
    size: 65,
  },
  {
    id: '4',
    name: 'NextByte',
    email: 'hello@nextbyte.sk',
    phone: '+421 905 123 456',
    location: 'Bratislava, Slovakia',
    type: UserType.Company,
    registeredAt: new Date('2022-01-12'),
    updatedAt: new Date(),
    companyName: 'NextByte',
    website: 'https://nextbyte.sk',
    description: 'Custom software house building scalable backend APIs and dashboards.',
    logoUrl: '/logos/nextbyte.png',
    industry: 'Custom Software',
    size: 40,
  },
  {
    id: '5',
    name: 'FrontendForce',
    email: 'team@frontendforce.cz',
    phone: '+420 234 567 890',
    location: 'Brno, Czech Republic',
    type: UserType.Company,
    registeredAt: new Date('2020-06-05'),
    updatedAt: new Date(),
    companyName: 'FrontendForce',
    website: 'https://frontendforce.cz',
    description: 'Specialists in frontend engineering using modern JavaScript frameworks.',
    logoUrl: '/logos/frontendforce.png',
    industry: 'Frontend Development',
    size: 30,
  },
  {
    id: '6',
    name: 'AI Dev',
    email: 'support@aidev.at',
    phone: '+43 664 112233',
    location: 'Linz, Austria',
    type: UserType.Company,
    registeredAt: new Date('2018-09-15'),
    updatedAt: new Date(),
    companyName: 'AI Dev',
    website: 'https://aidev.at',
    description: 'R&D startup delivering AI-powered predictive systems.',
    logoUrl: '/logos/aidev.png',
    industry: 'Artificial Intelligence',
    size: 25,
  },
  {
    id: '7',
    name: 'CloudWorks',
    email: 'info@cloudworks.de',
    phone: '+49 89 7654 3210',
    location: 'Munich, Germany',
    type: UserType.Company,
    registeredAt: new Date('2021-02-25'),
    updatedAt: new Date(),
    companyName: 'CloudWorks',
    website: 'https://cloudworks.de',
    description: 'Cloud-native consulting company for SaaS product development.',
    logoUrl: '/logos/cloudworks.png',
    industry: 'Cloud Computing',
    size: 100,
  },
  {
    id: '8',
    name: 'UX Spark',
    email: 'team@uxspark.sk',
    phone: '+421 944 888 777',
    location: 'Košice, Slovakia',
    type: UserType.Company,
    registeredAt: new Date('2023-04-18'),
    updatedAt: new Date(),
    companyName: 'UX Spark',
    website: 'https://uxspark.sk',
    description: 'UX/UI design and product strategy firm helping startups grow.',
    logoUrl: '/logos/uxspark.png',
    industry: 'UX/UI Design',
    size: 15,
  },
];

export default companies;
