import EmploymentType from "@/models/enums/EmploymentType";

const UsersDummyData = [
  {
    id: "1",
    name: "John Doe",
    email: "john@example.com",
    phone: "123-456-7890",
    bio: `I specialize in building modern web applications using React, Next.js, and Tailwind CSS, with a strong focus on performance, accessibility, and design systems. With 3+ years of experience, I've contributed to scalable projects ranging from e-commerce platforms to internal tools.

I enjoy collaborating with designers, working in agile teams, and turning complex ideas into intuitive user experiences. I'm always learning and staying up-to-date with the latest in front-end development and UI/UX best practices.

Currently exploring: TypeScript, React Server Components, and AI-driven UI tools.`,
    location: "New York, NY",
    skills: ["JavaScript", "React", "Node.js"],
    preferences: {
      locations: ["New York, NY", "San Francisco, CA"],
      remotePercentage: 51,
      employmentTypes: [EmploymentType.FullTime, EmploymentType.Contract],
      salaryMin: 60000,
      salaryMax: 90000,
    },
    registeredAt: new Date("2022-01-15"),
    updatedAt: new Date("2022-09-20"),
  },
  {
    id: "2",
    name: "Alice Smith",
    email: "alice@example.com",
    phone: "987-654-3210",
    bio: "Front-end developer with a passion for user interfaces.",
    location: "San Francisco, CA",
    skills: ["HTML", "CSS", "React"],
    preferences: {
      locations: ["San Francisco, CA"],
      remotePercentage: 30,
      employmentTypes: [EmploymentType.FullTime],
      salaryMin: 70000,
      salaryMax: 100000,
    },
    registeredAt: new Date("2021-11-05"),
    updatedAt: new Date("2022-08-10"),
  },
  {
    id: "3",
    name: "Bob Johnson",
    email: "bob@example.com",
    phone: "555-555-5555",
    bio: "Software engineer with a passion for open-source projects.",
    location: "Los Angeles, CA",
    skills: ["JavaScript", "Node.js", "Python"],
    preferences: {
      locations: ["Los Angeles, CA", "San Diego, CA"],
      remotePercentage: 20,
      employmentTypes: [EmploymentType.FullTime],
      salaryMin: 80000,
      salaryMax: 110000,
    },
    registeredAt: new Date("2022-03-12"),
    updatedAt: new Date("2022-10-25"),
  },
  {
    id: "4",
    name: "Eva Williams",
    email: "eva@example.com",
    phone: "123-987-4560",
    bio: "Product manager with experience in agile development.",
    location: "Austin, TX",
    skills: ["Product Management", "Agile", "Scrum"],
    preferences: {
      locations: ["Austin, TX"],
      remotePercentage: 10,
      employmentTypes: [EmploymentType.FullTime],
      salaryMin: 90000,
      salaryMax: 120000,
    },
    registeredAt: new Date("2022-02-28"),
    updatedAt: new Date("2022-09-15"),
  },
  {
    id: "5",
    name: "Mary Jackson",
    email: "mary@example.com",
    phone: "555-123-4567",
    bio: "Experienced UI/UX designer with a love for creative work.",
    location: "Chicago, IL",
    skills: ["UI Design", "UX Design", "Figma"],
    preferences: {
      locations: ["Chicago, IL"],
      remotePercentage: 40,
      employmentTypes: [EmploymentType.FullTime, EmploymentType.Contract],
      salaryMin: 75000,
      salaryMax: 100000,
    },
    registeredAt: new Date("2022-06-10"),
    updatedAt: new Date("2022-12-12"),
  },
  {
    id: "6",
    name: "David Brown",
    email: "david@example.com",
    phone: "123-555-7890",
    bio: "Experienced data scientist passionate about data analysis.",
    location: "San Diego, CA",
    skills: ["Python", "Data Analysis", "Machine Learning"],
    preferences: {
      locations: ["San Diego, CA", "Los Angeles, CA"],
      remotePercentage: 25,
      employmentTypes: [EmploymentType.FullTime],
      salaryMin: 85000,
      salaryMax: 110000,
    },
    registeredAt: new Date("2021-12-04"),
    updatedAt: new Date("2022-08-21"),
  },
  {
    id: "7",
    name: "Linda Wilson",
    email: "linda@example.com",
    phone: "555-789-1234",
    bio: "Experienced marketing manager with a focus on digital marketing.",
    location: "Miami, FL",
    skills: ["Digital Marketing", "SEO", "Social Media"],
    preferences: {
      locations: ["Miami, FL"],
      remotePercentage: 60,
      employmentTypes: [EmploymentType.FullTime],
      salaryMin: 80000,
      salaryMax: 110000,
    },
    registeredAt: new Date("2022-01-25"),
    updatedAt: new Date("2022-10-11"),
  },
  {
    id: "8",
    name: "Michael Johnson",
    email: "michael@example.com",
    phone: "555-123-7890",
    bio: "Experienced iOS developer with a passion for mobile app development.",
    location: "San Jose, CA",
    skills: ["Swift", "iOS Development", "Objective-C"],
    preferences: {
      locations: ["San Jose, CA"],
      remotePercentage: 15,
      employmentTypes: [EmploymentType.FullTime],
      salaryMin: 85000,
      salaryMax: 105000,
    },
    registeredAt: new Date("2022-02-19"),
    updatedAt: new Date("2022-09-30"),
  },
  {
    id: "9",
    name: "Olivia Davis",
    email: "olivia@example.com",
    phone: "555-789-4567",
    bio: "Creative graphic designer specializing in visual communication.",
    location: "Denver, CO",
    skills: ["Graphic Design", "Illustration", "Web Design"],
    preferences: {
      locations: ["Denver, CO"],
      remotePercentage: 20,
      employmentTypes: [EmploymentType.FullTime, EmploymentType.PartTime],
      salaryMin: 70000,
      salaryMax: 90000,
    },
    registeredAt: new Date("2022-03-29"),
    updatedAt: new Date("2022-11-14"),
  },
  {
    id: "10",
    name: "Sophia Wilson",
    email: "sophia@example.com",
    phone: "123-555-7890",
    bio: "Quality assurance engineer dedicated to ensuring software quality.",
    location: "Boston, MA",
    skills: ["Quality Assurance", "Testing", "Selenium"],
    preferences: {
      locations: ["Boston, MA", "New York, NY"],
      remotePercentage: 10,
      employmentTypes: [EmploymentType.FullTime, EmploymentType.Contract],
      salaryMin: 80000,
      salaryMax: 100000,
    },
    registeredAt: new Date("2022-04-15"),
    updatedAt: new Date("2022-10-30"),
  },
  {
    id: "11",
    name: "William Miller",
    email: "william@example.com",
    phone: "123-123-1234",
    bio: "Software engineer passionate about building innovative software solutions.",
    location: "Seattle, WA",
    skills: ["JavaScript", "React", "Node.js"],
    preferences: {
      locations: ["Seattle, WA"],
      remotePercentage: 40,
      employmentTypes: [EmploymentType.FullTime, EmploymentType.PartTime],
      salaryMin: 90000,
      salaryMax: 110000,
    },
    registeredAt: new Date("2022-05-20"),
    updatedAt: new Date("2022-12-15"),
  },
];

export default UsersDummyData;
