import Skill from '@/models/Skill';

const skills: Skill[] = [
  { id: '1', name: 'JavaScript' },
  { id: '2', name: 'TypeScript' },
  { id: '3', name: 'HTML' },
  { id: '4', name: 'CSS' },
  { id: '5', name: 'SASS' },
  { id: '6', name: 'Tailwind CSS' },
  { id: '7', name: 'React' },
  { id: '8', name: 'Next.js' },
  { id: '9', name: 'Redux' },
  { id: '10', name: 'Zustand' },
  { id: '11', name: 'React Native' },
  { id: '12', name: 'Vue.js' },
  { id: '13', name: 'Nuxt' },
  { id: '14', name: 'Angular' },
  { id: '15', name: 'Node.js' },
  { id: '16', name: 'Express.js' },
  { id: '17', name: 'GraphQL' },
  { id: '18', name: 'REST API' },
  { id: '19', name: 'MongoDB' },
  { id: '20', name: 'PostgreSQL' },
  { id: '21', name: 'MySQL' },
  { id: '22', name: 'Prisma' },
  { id: '23', name: 'Firebase' },
  { id: '24', name: 'AWS' },
  { id: '25', name: 'Docker' },
  { id: '26', name: 'Kubernetes' },
  { id: '27', name: 'CI/CD' },
  { id: '28', name: 'Jenkins' },
  { id: '29', name: 'Git' },
  { id: '30', name: 'GitOps' },
  { id: '31', name: 'Terraform' },
  { id: '32', name: 'Webpack' },
  { id: '33', name: 'Vite' },
  { id: '34', name: 'Babel' },
  { id: '35', name: 'Jest' },
  { id: '36', name: 'Testing Library' },
  { id: '37', name: 'Cypress' },
  { id: '38', name: 'Selenium' },
  { id: '39', name: 'Test Automation' },
  { id: '40', name: 'Continuous Testing' },
  { id: '41', name: 'Quality Assurance' },
  { id: '42', name: 'Figma' },
  { id: '43', name: 'Adobe XD' },
  { id: '44', name: 'Sketch' },
  { id: '45', name: 'InVision' },
  { id: '46', name: 'UI/UX Design' },
  { id: '47', name: 'Interaction Design' },
  { id: '48', name: 'Wireframing' },
  { id: '49', name: 'User-Centered Design' },
  { id: '50', name: 'User Research' },
  { id: '51', name: 'Agile' },
  { id: '52', name: 'Scrum' },
  { id: '53', name: 'JIRA' },
  { id: '54', name: 'Confluence' },
  { id: '55', name: 'Product Management' },
  { id: '56', name: 'SQL' },
  { id: '57', name: 'Python' },
  { id: '58', name: 'Django' },
  { id: '59', name: 'Flask' },
  { id: '60', name: 'Java' },
  { id: '61', name: '.NET' },
  { id: '62', name: 'Swift' },
  { id: '63', name: 'iOS Development' },
  { id: '64', name: 'UIKit' },
  { id: '65', name: 'Objective-C' },
  { id: '66', name: 'Xcode' },
  { id: '67', name: 'Machine Learning' },
  { id: '68', name: 'Deep Learning' },
  { id: '69', name: 'Natural Language Processing' },
  { id: '70', name: 'TensorFlow' },
  { id: '71', name: 'R' },
  { id: '72', name: 'Data Analysis' },
  { id: '73', name: 'Big Data' },
  { id: '74', name: 'Tableau' },
  { id: '75', name: 'Material-UI' },
  { id: '76', name: 'UI Design' },
  { id: '77', name: 'Responsive Web Design' },
  { id: '78', name: 'Performance Optimization' },
  { id: '79', name: 'Code Review' },
  { id: '80', name: 'Digital Marketing' },
  { id: '81', name: 'SEO' },
  { id: '82', name: 'Content Marketing' },
  { id: '83', name: 'Email Marketing' },
  { id: '84', name: 'Social Media' },
  { id: '85', name: 'Google Ads' },
  { id: '86', name: 'Video Editing' },
  { id: '87', name: 'Graphic Design' },
  { id: '88', name: 'Illustration' },
  { id: '89', name: 'Adobe Creative Suite' },
  { id: '90', name: 'Illustrator' },
];

export default skills;
