import { ExistingCompany } from '@/models/Company';

const companies: ExistingCompany[] = [
  {
    id: '1',
    name: 'SoftVision',
    email: 'info@softvision.cz',
    location: 'Prague, Czech Republic',
    description: 'Czech software development agency specializing in web and mobile apps.',
    website: 'https://softvision.cz',
    logoUrl: '/logos/softvision.png',
    industry: 'IT Services',
    size: 150,
    isVerified: true,
    createdAt: new Date('2021-03-01'),
    updatedAt: new Date(),
  },
  {
    id: '2',
    name: 'CodeRealm GmbH',
    email: 'contact@coderealm.de',
    location: 'Berlin, Germany',
    description: 'Full-stack development firm offering enterprise solutions in Java and React.',
    website: 'https://coderealm.de',
    logoUrl: '/logos/coderealm.png',
    industry: 'Software Development',
    size: 60,
    isVerified: true,
    createdAt: new Date('2020-08-10'),
    updatedAt: new Date(),
  },
  {
    id: '3',
    name: 'TechAustria',
    email: 'office@techaustria.at',
    location: 'Vienna, Austria',
    description: 'Austrian tech firm focused on IoT, embedded systems, and AI.',
    website: 'https://techaustria.at',
    logoUrl: '/logos/techaustria.png',
    industry: 'Embedded Systems',
    size: 120,
    isVerified: true,
    createdAt: new Date('2019-11-20'),
    updatedAt: new Date(),
  },
  {
    id: '4',
    name: 'NextByte',
    email: 'hello@nextbyte.sk',
    location: 'Bratislava, Slovakia',
    description: 'Custom software house building scalable backend APIs and dashboards.',
    website: 'https://nextbyte.sk',
    logoUrl: '/logos/nextbyte.png',
    industry: 'Custom Software',
    size: 40,
    isVerified: true,
    createdAt: new Date('2022-01-12'),
    updatedAt: new Date(),
  },
  {
    id: '5',
    name: 'FrontendForce',
    email: 'team@frontendforce.cz',
    location: 'Brno, Czech Republic',
    description: 'Specialists in frontend engineering using modern JavaScript frameworks.',
    website: 'https://frontendforce.cz',
    logoUrl: '/logos/frontendforce.png',
    industry: 'Frontend Development',
    size: 30,
    isVerified: true,
    createdAt: new Date('2020-06-05'),
    updatedAt: new Date(),
  },
  {
    id: '6',
    name: 'AI Dev',
    email: 'support@aidev.at',
    location: 'Linz, Austria',
    description: 'R&D startup delivering AI-powered predictive systems.',
    website: 'https://aidev.at',
    logoUrl: '/logos/aidev.png',
    industry: 'Artificial Intelligence',
    size: 50,
    isVerified: true,
    createdAt: new Date('2018-09-15'),
    updatedAt: new Date(),
  },
  {
    id: '7',
    name: 'CloudWorks',
    email: 'info@cloudworks.de',
    location: 'Munich, Germany',
    description: 'Cloud-native consulting company for SaaS product development.',
    website: 'https://cloudworks.de',
    logoUrl: '/logos/cloudworks.png',
    industry: 'Cloud Computing',
    size: 200,
    isVerified: true,
    createdAt: new Date('2021-02-25'),
    updatedAt: new Date(),
  },
  {
    id: '8',
    name: 'UX Spark',
    email: 'team@uxspark.sk',
    location: 'Košice, Slovakia',
    description: 'UX/UI design and product strategy firm helping startups grow.',
    website: 'https://uxspark.sk',
    logoUrl: '/logos/uxspark.png',
    industry: 'UX/UI Design',
    size: 50,
    isVerified: true,
    createdAt: new Date('2023-04-18'),
    updatedAt: new Date(),
  },
];

export default companies;
